"""核心模块 —— Markdown 语法模板与生成工具。"""

from .markdown_utils import (
    build_frontmatter,
    admonition_snippet,
    image_grid_snippet,
    github_card_snippet,
    spoiler_snippet,
    video_snippet,
    details_snippet,
    code_block_snippet,
    mermaid_snippet,
    plantuml_snippet,
    katex_snippet,
    table_snippet,
    FRONTMATTER_FIELDS,
    FRONTMATTER_ORDER,
    GITHUB_CALLOUT_TYPES,
    OBSIDIAN_CALLOUT_TYPES,
    VITEPRESS_CALLOUT_TYPES,
    DOCUSAURUS_CALLOUT_TYPES,
    CALLOUT_STYLES,
    MERMAID_TEMPLATES,
    PLANTUML_TEMPLATES,
    KATEX_EXAMPLES,
)

__all__ = [
    "build_frontmatter",
    "admonition_snippet",
    "image_grid_snippet",
    "github_card_snippet",
    "spoiler_snippet",
    "video_snippet",
    "details_snippet",
    "code_block_snippet",
    "mermaid_snippet",
    "plantuml_snippet",
    "katex_snippet",
    "table_snippet",
    "FRONTMATTER_FIELDS",
    "FRONTMATTER_ORDER",
    "GITHUB_CALLOUT_TYPES",
    "OBSIDIAN_CALLOUT_TYPES",
    "VITEPRESS_CALLOUT_TYPES",
    "DOCUSAURUS_CALLOUT_TYPES",
    "CALLOUT_STYLES",
    "MERMAID_TEMPLATES",
    "PLANTUML_TEMPLATES",
    "KATEX_EXAMPLES",
]
